//sDNA software for spatial network analysis 
//Copyright (C) 2011-2019 Cardiff University

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

//unique ids for edges and links generated by the network object

template<class T> class UniqueIdGenerator;

template <class T> struct UniqueId 
{
	size_t id;
	explicit UniqueId (size_t i) : id(i) {}
	UniqueId() : id(-1) {}
	inline bool operator==(const UniqueId<T> &other) const
	{
		return (this->id==other.id);
	}
	typedef T indexed_class_type;
};

template <class ID> class IndexedObject
{
public:
	virtual inline ID get_id() const = 0;
};
