//sDNA software for spatial network analysis 
//Copyright (C) 2011-2019 Cardiff University

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

//THIS IS EITHER A TEMPLATE OR AN AUTOGENERATED FILE
//IF THE FILENAME IS version_generated.h DON'T EDIT IT - EDIT version_template.h INSTEAD!

const char *GIT_HASH = "#GITHASH#";
const char *BUILD_DATE = __DATE__;

#ifdef _DEBUG
const char *BUILD_CONFIG="debug";
#else
const char *BUILD_CONFIG="";
#endif

//do not change anything on this line except what's in the quotes
//python parses this file to pull out the version number
const char *SDNA_VERSION = "4.0.4";